# Generated by Django 4.0.3 on 2022-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия студента')),
                ('number_parents', models.IntegerField(verbose_name='Номер родителей')),
                ('place_of_residence', models.CharField(max_length=255, verbose_name='Место проживания')),
                ('photo_student', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='Фото студента')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
