# Generated by Django 4.0.3 on 2022-03-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
    ]
