# Generated by Django 4.0.3 on 2022-03-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0003_alter_lesson_options'),
        ('teacher', '0002_alter_teacher_options'),
        ('students', '0002_students_klass'),
        ('klass', '0002_alter_classroom_options'),
        ('headteacher', '0002_alter_headteacher_options_and_more'),
        ('director', '0002_alter_director_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shkola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название школы')),
                ('director', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.director')),
                ('head_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='headteacher.headteacher')),
                ('klass', models.ManyToManyField(null=True, to='klass.classroom')),
                ('lessons', models.ManyToManyField(null=True, to='lesson.lesson')),
                ('students', models.ManyToManyField(null=True, to='students.students')),
                ('teachers', models.ManyToManyField(null=True, to='teacher.teacher')),
            ],
        ),
    ]
