# Generated by Django 4.0.3 on 2022-03-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директоры'},
        ),
    ]
